version: '3'
services:
  yiiapp_php:
    build:
      context: ./
      dockerfile: php.dockerfile
    image: yiiapp-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./runtime:/app/runtime:delegated
      - ./web/assets:/app/web/assets:delegated
    ports:
      - ${APACHE_PORT}:80
    container_name: yiiapp-php
    restart: always
    environment:
      TZ: "Europe/Kiev"
      XDEBUG_CONFIG: "remote_host=${LOCALHOST}"
      PHP_ENABLE_XDEBUG: "1"
    links:
      - yiiapp_mysql
  yiiapp_mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --sql_mode=''
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    container_name: yiiapp-mysql
    volumes:
      - ./yiiapp_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
volumes:
  yiiapp_db: